# Extra autostart processes
# exec-once = uwsm-app -- my-service

# set cursor theme
exec-once = hyprctl setcursor "WhiteSur cursors" 24

# start librepods with a delay to ensure BlueZ is up
exec-once = sleep 10 && librepods
